spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: '{cipher}6efbcba179a09880e212a9dbc39b0f5fc3477a4452c8d70b7b31ae03a18ef6f685d4bfa497d00e6133f5db0bad04c9eb'